#define GEO_TRUST_GLOBAL_CA \
"-----BEGIN CERTIFICATE-----\r\n" \
"MIIDVDCCAjygAwIBAgIDAjRWMA0GCSqGSIb3DQEBBQUAMEIxCzAJBgNVBAYTAlVT\r\n" \
"MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i\r\n" \
"YWwgQ0EwHhcNMDIwNTIxMDQwMDAwWhcNMjIwNTIxMDQwMDAwWjBCMQswCQYDVQQG\r\n" \
"EwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEbMBkGA1UEAxMSR2VvVHJ1c3Qg\r\n" \
"R2xvYmFsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2swYYzD9\r\n" \
"9BcjGlZ+W988bDjkcbd4kdS8odhM+KhDtgPpTSEHCIjaWC9mOSm9BXiLnTjoBbdq\r\n" \
"fnGk5sRgprDvgOSJKA+eJdbtg/OtppHHmMlCGDUUna2YRpIuT8rxh0PBFpVXLVDv\r\n" \
"iS2Aelet8u5fa9IAjbkU+BQVNdnARqN7csiRv8lVK83Qlz6cJmTM386DGXHKTubU\r\n" \
"1XupGc1V3sjs0l44U+VcT4wt/lAjNvxm5suOpDkZALeVAjmRCw7+OC7RHQWa9k0+\r\n" \
"bw8HHa8sHo9gOeL6NlMTOdReJivbPagUvTLrGAMoUgRx5aszPeE4uwc2hGKceeoW\r\n" \
"MPRfwCvocWvk+QIDAQABo1MwUTAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTA\r\n" \
"ephojYn7qwVkDBF9qn1luMrMTjAfBgNVHSMEGDAWgBTAephojYn7qwVkDBF9qn1l\r\n" \
"uMrMTjANBgkqhkiG9w0BAQUFAAOCAQEANeMpauUvXVSOKVCUn5kaFOSPeCpilKIn\r\n" \
"Z57QzxpeR+nBsqTP3UEaBU6bS+5Kb1VSsyShNwrrZHYqLizz/Tt1kL/6cdjHPTfS\r\n" \
"tQWVYrmm3ok9Nns4d0iXrKYgjy6myQzCsplFAMfOEVEiIuCl6rYVSAlk6l5PdPcF\r\n" \
"PseKUgzbFbS9bZvlxrFUaKnjaZC2mqUPuLk/IH2uSrW4nOQdtqvmlKXBx4Ot2/Un\r\n" \
"hw4EbNX/3aBd7YdStysVAq45pmp06drE57xNNB6pXE0zX5IJL4hmXXeXxx12E6nV\r\n" \
"5fEWCRE11azbJHFwLJhWC9kXtNHjUStedejV0NxPNO3CBWaAocvmMw==\r\n" \
"-----END CERTIFICATE-----\r\n"

#define CLAVE_CA \
"-----BEGIN CERTIFICATE-----\r\n" \
"MIIDBjCCAe4CCQDl9Bfq++fJtDANBgkqhkiG9w0BAQsFADBFMQswCQYDVQQGEwJB\r\n" \
"VTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0\r\n" \
"cyBQdHkgTHRkMB4XDTE3MDYwMjA3MDU0N1oXDTE3MDcwMjA3MDU0N1owRTELMAkG\r\n" \
"A1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0\r\n" \
"IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\r\n" \
"ALuaANRf/AbXLWe7f4WXntHzuK+6ravJPPR/5Fe+0pFv+8sZGCPM6FGDvBGW6/F4\r\n" \
"rLE8wfKZZYQgnv66UwWHncARqwI++DCwxiHt+uFo2hbLrinULcqIN4iUFUR5lWw7\r\n" \
"NxvpPXF0WBvWSlAq5i73Xvn3FODVAef+N7B6ylP+DKAkzMN49Ze8NSscz79edGWy\r\n" \
"fI9/mSICc1BT2Sag58BOEQTFqrTITDWoHiiC12yLfTiWWGSRK0D1ACQSfcNy11g5\r\n" \
"FwKJlgPUOZHQvlGpCwWt3jgqbsvOqNVgtuucgyEZ+AoKrX+glnNS3YbtosM2c67V\r\n" \
"KQf186rYkc/v59RYHwM414sCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEARof4JToJ\r\n" \
"e0mDDZpOTFl4HbR5PMmQaiZdJJU1nWmhYOtFoOz7k+ZzLvefJ2XrYXFtoUwipVEJ\r\n" \
"AuH9FjuEuDnHTG6YHkCnGscovq+wpX57d/ZIw6op6JFAX6mDVoEozar5/hLIjAcd\r\n" \
"QHUTk8eWkYDewC44TdLGhIndWQLXPce+K32SvUW5eZVvSDeJehrb+UJDEzdwefUv\r\n" \
"LUFUz4LcB5nEdujIstijUz3BDFCr6F6TYNOpsLIsvRkE/lfOhcHxPh8YAfDdi1ES\r\n" \
"Op3/08R8kK9obe8HXJUufqx1oZ01zqPJwB7UE2Z7e6/VzdJvKdv/+sSd4J6R3V1c\r\n" \
"UQMTQEOtvopQ5w==\r\n" \
"-----END CERTIFICATE-----\r\n"

const char root_cas_pem[] = \
GEO_TRUST_GLOBAL_CA \
CLAVE_CA;
const size_t root_cas_pem_len = sizeof(root_cas_pem);
