#define GEO_TRUST_GLOBAL_CA \
"-----BEGIN CERTIFICATE-----\r\n" \
"MIIDVDCCAjygAwIBAgIDAjRWMA0GCSqGSIb3DQEBBQUAMEIxCzAJBgNVBAYTAlVT\r\n" \
"MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i\r\n" \
"YWwgQ0EwHhcNMDIwNTIxMDQwMDAwWhcNMjIwNTIxMDQwMDAwWjBCMQswCQYDVQQG\r\n" \
"EwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEbMBkGA1UEAxMSR2VvVHJ1c3Qg\r\n" \
"R2xvYmFsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2swYYzD9\r\n" \
"9BcjGlZ+W988bDjkcbd4kdS8odhM+KhDtgPpTSEHCIjaWC9mOSm9BXiLnTjoBbdq\r\n" \
"fnGk5sRgprDvgOSJKA+eJdbtg/OtppHHmMlCGDUUna2YRpIuT8rxh0PBFpVXLVDv\r\n" \
"iS2Aelet8u5fa9IAjbkU+BQVNdnARqN7csiRv8lVK83Qlz6cJmTM386DGXHKTubU\r\n" \
"1XupGc1V3sjs0l44U+VcT4wt/lAjNvxm5suOpDkZALeVAjmRCw7+OC7RHQWa9k0+\r\n" \
"bw8HHa8sHo9gOeL6NlMTOdReJivbPagUvTLrGAMoUgRx5aszPeE4uwc2hGKceeoW\r\n" \
"MPRfwCvocWvk+QIDAQABo1MwUTAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTA\r\n" \
"ephojYn7qwVkDBF9qn1luMrMTjAfBgNVHSMEGDAWgBTAephojYn7qwVkDBF9qn1l\r\n" \
"uMrMTjANBgkqhkiG9w0BAQUFAAOCAQEANeMpauUvXVSOKVCUn5kaFOSPeCpilKIn\r\n" \
"Z57QzxpeR+nBsqTP3UEaBU6bS+5Kb1VSsyShNwrrZHYqLizz/Tt1kL/6cdjHPTfS\r\n" \
"tQWVYrmm3ok9Nns4d0iXrKYgjy6myQzCsplFAMfOEVEiIuCl6rYVSAlk6l5PdPcF\r\n" \
"PseKUgzbFbS9bZvlxrFUaKnjaZC2mqUPuLk/IH2uSrW4nOQdtqvmlKXBx4Ot2/Un\r\n" \
"hw4EbNX/3aBd7YdStysVAq45pmp06drE57xNNB6pXE0zX5IJL4hmXXeXxx12E6nV\r\n" \
"5fEWCRE11azbJHFwLJhWC9kXtNHjUStedejV0NxPNO3CBWaAocvmMw==\r\n" \
"-----END CERTIFICATE-----\r\n"

#define CLAVE_CA \
"-----BEGIN CERTIFICATE-----\r\n" \
"MIIDKDCCAhACCQCMsNx3BhfN4jANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJD\r\n" \
"TjELMAkGA1UECAwCU0gxCzAJBgNVBAcMAk1IMQ0wCwYDVQQKDAROb25lMQ0wCwYD\r\n" \
"VQQLDAROb25lMQ8wDQYDVQQDDAZSb290Q0EwHhcNMTcwNTAzMDg1ODQ0WhcNMTcw\r\n" \
"NjAyMDg1ODQ0WjBWMQswCQYDVQQGEwJDTjELMAkGA1UECAwCU0gxCzAJBgNVBAcM\r\n" \
"Ak1IMQ0wCwYDVQQKDAROb25lMQ0wCwYDVQQLDAROb25lMQ8wDQYDVQQDDAZSb290\r\n" \
"Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAI3+KapxKbp58irWd\r\n" \
"+zrp+WyvNFASA9m+T6uswxGhm8LaYjKAkpeLhrZxDbrJ4Jok473xncb4g95egV0w\r\n" \
"QUwFbg/Ze7PlEu7Annp5DU0nZ7GSSLkVyB/hBARZG0JCo9A/yN1uOvSX7NW2Y7Ro\r\n" \
"liktxfRuqyjcW/9izdZ7WW0wOVAEm+3M++BrEvsJDq6XtRdB6qNuleYyC1/i81my\r\n" \
"J5ps5D6yg92q3vHjGb+8liY/iQI3wIFug0Or3m1BQmYgSY60s33P/Fsgyr1qOnP3\r\n" \
"qgsA81FbuDJopR3inQ+bzWQXFo77bpX6vOWV5dHf8icJF8DQ6hPdl9YAcwLG8nXC\r\n" \
"FO6vAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAKt3KJ6rcSZajWfBad9aFVarnlnS\r\n" \
"sbhRKUzmyg6iuWfQzNV6KAB9IEu1pqptYDKX6teMglepz4+l5rptlKBreXxwuDYO\r\n" \
"VeqEzriDPDVkcodqSc3fpmXzeaVsgPqmgcDleI1TGjqxTXQ5Upw1vmjq4uiViKHZ\r\n" \
"ezTw8J0lRZ1jG4evm4MQ5aA6duoy/cJILS8EHW612pqNHAzUedMJqsuiSl/WoEJn\r\n" \
"4GzZK6FyyMUNMZzp0+hhOHQ3ZSIgIAq1Rp+mEDre6Ny4olJovyEBPf6b1AtTlO4a\r\n" \
"T7/7VK2bFkEq6HGgKVvpaA/pYVP/IVuo4IEclMiN/3fSOG5cLW7QNGPkIw8=\r\n" \
"-----END CERTIFICATE-----\r\n"

const char root_cas_pem[] = \
GEO_TRUST_GLOBAL_CA \
CLAVE_CA;
const size_t root_cas_pem_len = sizeof(root_cas_pem);
